"""empty message

Revision ID: e5626391e2a0
Revises: 
Create Date: 2023-05-23 17:46:52.116096

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from src.repository import create_roles, create_admin


# revision identifiers, used by Alembic.
revision = 'e5626391e2a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    create_roles()
    create_admin()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###